name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: egor-tensin/setup-cygwin@v3
      - name: cygwin
        with:
          platform: x64
          packages: gcc
        run: |
          gcc -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -d
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          gcc -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -d
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          gcc -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -d
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: release
        run: |
          clang -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -r -s
