name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -o igncr '{0}'   
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        uses: egor-tensin/setup-cygwin@v3
      - run: |
          gcc -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -r
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          gcc -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -d
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          gcc -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -d
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: release
        run: |
          clang -Wall -Werror -Wextra -pthread -O3 ./nobuild.c -o ./nobuild
          ./nobuild -r -s
